# decompyle3 version 3.9.3
# Python bytecode version base 3.8.0 (3413)
# Decompiled from: Python 3.14.4 | packaged by Anaconda, Inc. | (main, Apr 14 2026, 17:00:17) [MSC v.1942 64 bit (AMD64)]
# Embedded file name: /var/jenkins_home/workspace/IngenicX2600-CFS-C-Master-Security-Build/integrated_platform/buildtools/../creality/output/build/klipper-creality/klippy/extras/ad5206.py
# Compiled at: 2025-10-29 02:45:24
# Size of source mod 2**32: 785 bytes
               expr ::= LOAD_CONST (1)
               return_expr ::= expr (1)
         2     expr ::= LOAD_CONST (2)
         8     store ::= STORE_NAME (5)
         6-8   alias ::= IMPORT_FROM store (5)
         6     importlist ::= alias (5)
               import_from ::= LOAD_CONST LOAD_CONST IMPORT_NAME importlist POP_TOP (6)
               stmt ::= import_from (6)
               stmts ::= stmt (6)
               sstmt ::= stmt (6)
               c_stmt ::= stmt (6)
               START ::= |- stmts (6)
               _stmts ::= stmts (6)
               stmts ::= sstmt (6)
               c_stmts ::= c_stmt (6)
               c_stmts ::= _stmts (6)
        14-18  mkfunc ::= LOAD_CODE LOAD_STR MAKE_FUNCTION_0 (10)
        20     expr ::= LOAD_STR (11)
L.  8:  12-22  build_class ::= LOAD_BUILD_CLASS mkfunc expr CALL_FUNCTION_2 (12)
        24     store ::= STORE_NAME (13)
L.  8:  12-24  classdef ::= build_class store (13)
L.  8:  12     stmt ::= classdef (13)
               stmts ::= stmts stmt (13)
L.  8:  12     stmts ::= stmt (13)
L.  8:  12     sstmt ::= stmt (13)
L.  8:  12     c_stmt ::= stmt (13)
               START ::= |- stmts (13)
               _stmts ::= stmts (13)
L.  8:  12     _stmts ::= stmts (13)
               stmts ::= stmts sstmt (13)
L.  8:  12     stmts ::= sstmt (13)
L.  8:  12     c_stmts ::= c_stmt (13)
               c_stmts ::= c_stmts c_stmt (13)
               c_stmts ::= _stmts (13)
L.  8:  12     c_stmts ::= _stmts (13)
L. 21:  26     expr ::= LOAD_CODE (14)
L. 21:  26     expr ::= LOAD_CODE (14)
L. 21:  26     return_expr ::= expr (14)
L. 21:  26     return_expr ::= expr (14)
        28     expr ::= LOAD_STR (15)
L. 21:  26-30  mkfunc ::= LOAD_CODE LOAD_STR MAKE_FUNCTION_0 (16)
               store ::= STORE_NAME (17)
               function_def ::= mkfunc store (17)
               stmt ::= function_def (17)
               stmts ::= stmts stmt (17)
               stmts ::= stmt (17)
               sstmt ::= stmt (17)
               c_stmt ::= stmt (17)
               stmts ::= stmts stmt (17)
               START ::= |- stmts (17)
               _stmts ::= stmts (17)
               _stmts ::= stmts (17)
               stmts ::= stmts sstmt (17)
               stmts ::= sstmt (17)
               stmts ::= stmts sstmt (17)
               c_stmts ::= c_stmt (17)
               c_stmts ::= c_stmts c_stmt (17)
               c_stmts ::= c_stmts c_stmt (17)
               _stmts ::= stmts (17)
               c_stmts ::= _stmts (17)
               c_stmts ::= _stmts (17)
               c_stmts ::= _stmts (17)
               expr ::= LOAD_NAME (1)
               return_expr ::= expr (1)
         2     store ::= STORE_NAME (2)
               assign ::= expr store (2)
               stmt ::= assign (2)
               stmts ::= stmt (2)
               sstmt ::= stmt (2)
               c_stmt ::= stmt (2)
               START ::= |- stmts (2)
               _stmts ::= stmts (2)
               stmts ::= sstmt (2)
               c_stmts ::= c_stmt (2)
               c_stmts ::= _stmts (2)
         4     expr ::= LOAD_STR (3)
         4     return_expr ::= expr (3)
         4     return_expr ::= expr (3)
         6     store ::= STORE_NAME (4)
         4-6   assign ::= expr store (4)
         4     stmt ::= assign (4)
               stmts ::= stmts stmt (4)
         4     stmts ::= stmt (4)
         4     sstmt ::= stmt (4)
         4     c_stmt ::= stmt (4)
               START ::= |- stmts (4)
               _stmts ::= stmts (4)
         4     _stmts ::= stmts (4)
               stmts ::= stmts sstmt (4)
         4     stmts ::= sstmt (4)
         4     c_stmts ::= c_stmt (4)
               c_stmts ::= c_stmts c_stmt (4)
               c_stmts ::= _stmts (4)
         4     c_stmts ::= _stmts (4)
L.  9:   8     expr ::= LOAD_CODE (5)
L.  9:   8     expr ::= LOAD_CODE (5)
L.  9:   8     return_expr ::= expr (5)
L.  9:   8     return_expr ::= expr (5)
        10     expr ::= LOAD_STR (6)
L.  9:   8-12  mkfunc ::= LOAD_CODE LOAD_STR MAKE_FUNCTION_0 (7)
        14     store ::= STORE_NAME (8)
L.  9:   8-14  function_def ::= mkfunc store (8)
L.  9:   8     stmt ::= function_def (8)
               stmts ::= stmts stmt (8)
L.  9:   8     stmts ::= stmt (8)
L.  9:   8     sstmt ::= stmt (8)
L.  9:   8     c_stmt ::= stmt (8)
         4-14  stmts ::= stmts stmt (8)
               START ::= |- stmts (8)
               _stmts ::= stmts (8)
L.  9:   8     _stmts ::= stmts (8)
               stmts ::= stmts sstmt (8)
L.  9:   8     stmts ::= sstmt (8)
         4-14  stmts ::= stmts sstmt (8)
L.  9:   8     c_stmts ::= c_stmt (8)
         4-14  c_stmts ::= c_stmts c_stmt (8)
               c_stmts ::= c_stmts c_stmt (8)
         4     _stmts ::= stmts (8)
               c_stmts ::= _stmts (8)
L.  9:   8     c_stmts ::= _stmts (8)
         4     c_stmts ::= _stmts (8)
L. 18:  16     expr ::= LOAD_CODE (9)
L. 18:  16     expr ::= LOAD_CODE (9)
L. 18:  16     return_expr ::= expr (9)
L. 18:  16     return_expr ::= expr (9)
        18     expr ::= LOAD_STR (10)
L. 18:  16-20  mkfunc ::= LOAD_CODE LOAD_STR MAKE_FUNCTION_0 (11)
               store ::= STORE_NAME (12)
               function_def ::= mkfunc store (12)
               stmt ::= function_def (12)
               stmts ::= stmts stmt (12)
               stmts ::= stmt (12)
               sstmt ::= stmt (12)
               c_stmt ::= stmt (12)
               stmts ::= stmts stmt (12)
               stmts ::= stmts stmt (12)
               START ::= |- stmts (12)
               _stmts ::= stmts (12)
               _stmts ::= stmts (12)
               stmts ::= stmts sstmt (12)
               stmts ::= sstmt (12)
               stmts ::= stmts sstmt (12)
               stmts ::= stmts sstmt (12)
               c_stmts ::= c_stmt (12)
               c_stmts ::= c_stmts c_stmt (12)
               c_stmts ::= c_stmts c_stmt (12)
               c_stmts ::= c_stmts c_stmt (12)
               _stmts ::= stmts (12)
               _stmts ::= stmts (12)
               c_stmts ::= _stmts (12)
               c_stmts ::= _stmts (12)
               c_stmts ::= _stmts (12)
               c_stmts ::= _stmts (12)
               expr ::= LOAD_GLOBAL (1)
               return_expr ::= expr (1)
               attribute ::= expr LOAD_ATTR (2)
               expr ::= attribute (2)
               return_expr ::= expr (2)
L. 11:   4     expr ::= LOAD_FAST (3)
L. 11:   6     expr ::= LOAD_CONST (4)
L. 11:   8     expr ::= LOAD_STR (5)
L. 11:  10     expr ::= LOAD_CONST (6)
L. 10:  12     expr ::= LOAD_CONST (7)
               call_kw36 ::= expr expr expr expr expr LOAD_CONST CALL_FUNCTION_KW_4 (8)
               expr ::= call_kw36 (8)
               return_expr ::= expr (8)
        16     expr ::= LOAD_FAST (9)
        16-18  store ::= expr STORE_ATTR (10)
               assign ::= expr store (10)
               stmt ::= assign (10)
               stmts ::= stmt (10)
               sstmt ::= stmt (10)
               c_stmt ::= stmt (10)
               START ::= |- stmts (10)
               _stmts ::= stmts (10)
               stmts ::= sstmt (10)
               c_stmts ::= c_stmt (10)
               c_stmts ::= _stmts (10)
L. 12:  20     expr ::= LOAD_FAST (11)
L. 12:  20     return_expr ::= expr (11)
L. 12:  20     return_expr ::= expr (11)
L. 12:  20-22  attribute ::= expr LOAD_ATTR (12)
L. 12:  20     expr ::= attribute (12)
L. 12:  20     return_expr ::= expr (12)
L. 12:  20     return_expr ::= expr (12)
        24     expr ::= LOAD_STR (13)
        26     expr ::= LOAD_CONST (14)
        28     expr ::= LOAD_CONST (15)
        30     expr ::= LOAD_CONST (16)
L. 12:  20-32  call_kw36 ::= expr expr expr expr LOAD_CONST CALL_FUNCTION_KW_3 (17)
L. 12:  20     expr ::= call_kw36 (17)
L. 12:  20     return_expr ::= expr (17)
L. 12:  20     return_expr ::= expr (17)
        34     store ::= STORE_FAST (18)
L. 12:  20-34  assign ::= expr store (18)
L. 12:  20     stmt ::= assign (18)
               stmts ::= stmts stmt (18)
L. 12:  20     stmts ::= stmt (18)
L. 12:  20     sstmt ::= stmt (18)
L. 12:  20     c_stmt ::= stmt (18)
               START ::= |- stmts (18)
               _stmts ::= stmts (18)
L. 12:  20     _stmts ::= stmts (18)
               stmts ::= stmts sstmt (18)
L. 12:  20     stmts ::= sstmt (18)
L. 12:  20     c_stmts ::= c_stmt (18)
               c_stmts ::= c_stmts c_stmt (18)
               c_stmts ::= _stmts (18)
L. 12:  20     c_stmts ::= _stmts (18)
L. 13:  36     expr ::= LOAD_GLOBAL (19)
L. 13:  36     return_expr ::= expr (19)
L. 13:  36     return_expr ::= expr (19)
        38     expr ::= LOAD_CONST (20)
L. 13:  36-40  call ::= expr expr CALL_FUNCTION_1 (21)
L. 13:  36     expr ::= call (21)
L. 13:  36     return_expr ::= expr (21)
L. 13:  36     return_expr ::= expr (21)
L. 13:  36-42  get_iter ::= expr GET_ITER (22)
L. 13:  36     expr ::= get_iter (22)
L. 13:  36     return_expr ::= expr (22)
L. 13:  36     return_expr ::= expr (22)
        44-44  _come_froms ::= \e__come_froms COME_FROM (23)
        44-44  _come_froms ::= _come_froms COME_FROM (24)
        42-44  get_for_iter ::= GET_ITER _come_froms FOR_ITER (25)
        46     store ::= STORE_FAST (26)
L. 14:  48     expr ::= LOAD_FAST (27)
L. 14:  48     return_expr ::= expr (27)
L. 14:  48-50  attribute ::= expr LOAD_ATTR (28)
L. 14:  48     expr ::= attribute (28)
L. 14:  48     return_expr ::= expr (28)
        52     expr ::= LOAD_STR (29)
        54     expr ::= LOAD_FAST (30)
        56     expr ::= LOAD_CONST (31)
        58     binary_operator ::= BINARY_ADD (32)
        54-58  bin_op ::= expr expr binary_operator (32)
        54     expr ::= bin_op (32)
        54-60  tuple ::= expr BUILD_TUPLE_1 (33)
        54     expr ::= tuple (33)
        62     binary_operator ::= BINARY_MODULO (34)
        52-62  bin_op ::= expr expr binary_operator (34)
        52     expr ::= bin_op (34)
        64     expr ::= LOAD_CONST (35)
L. 15:  66     expr ::= LOAD_CONST (36)
L. 15:  68     expr ::= LOAD_FAST (37)
L. 14:  70     expr ::= LOAD_CONST (38)
L. 14:  48-72  call_kw36 ::= expr expr expr expr expr LOAD_CONST CALL_FUNCTION_KW_4 (39)
L. 14:  48     expr ::= call_kw36 (39)
L. 14:  48     return_expr ::= expr (39)
        74     store ::= STORE_FAST (40)
L. 14:  48-74  assign ::= expr store (40)
L. 14:  48     stmt ::= assign (40)
L. 14:  48     stmts ::= stmt (40)
L. 14:  48     sstmt ::= stmt (40)
L. 14:  48     c_stmt ::= stmt (40)
L. 14:  48     _stmts ::= stmts (40)
L. 14:  48     stmts ::= sstmt (40)
L. 14:  48     c_stmts ::= c_stmt (40)
L. 14:  48     c_stmts ::= _stmts (40)
L. 14:  48     for_block ::= c_stmts (40)
L. 14:  48     c_stmts_opt ::= c_stmts (40)
L. 13:  36-74  for38 ::= expr get_for_iter store for_block \e__come_froms (40)
Reduce for38 invalid by check
L. 16:  76     expr ::= LOAD_FAST (41)
L. 16:  76     return_expr ::= expr (41)
L. 16:  76     return_expr ::= expr (41)
        78     expr ::= LOAD_CONST (42)
L. 16:  76-80  compare_single ::= expr expr COMPARE_OP (43)
L. 16:  76     compare ::= compare_single (43)
L. 16:  76     expr ::= compare (43)
L. 16:  76     return_expr ::= expr (43)
L. 16:  76     return_expr ::= expr (43)
L. 16:  76-82  testtruec ::= expr POP_JUMP_IF_FALSE_LOOP (44)
L. 16:  76     testexprc ::= testtruec (44)
L. 17:  84     expr ::= LOAD_FAST (45)
L. 17:  84     return_expr ::= expr (45)
L. 17:  84-86  attribute37 ::= expr LOAD_METHOD (46)
L. 17:  84     expr ::= attribute37 (46)
L. 17:  84     return_expr ::= expr (46)
        88     expr ::= LOAD_FAST (47)
        90     expr ::= LOAD_GLOBAL (48)
        92     expr ::= LOAD_FAST (49)
        94     expr ::= LOAD_CONST (50)
        96     binary_operator ::= BINARY_MULTIPLY (51)
        92-96  bin_op ::= expr expr binary_operator (51)
        92     expr ::= bin_op (51)
        98     expr ::= LOAD_FAST (52)
       100     binary_operator ::= BINARY_TRUE_DIVIDE (53)
        92-100 bin_op ::= expr expr binary_operator (53)
        92     expr ::= bin_op (53)
       102     expr ::= LOAD_CONST (54)
       104     binary_operator ::= BINARY_ADD (55)
        92-104 bin_op ::= expr expr binary_operator (55)
        92     expr ::= bin_op (55)
        90-106 call ::= expr expr CALL_FUNCTION_1 (56)
        90     expr ::= call (56)
L. 17:  84-108 call ::= expr expr expr CALL_METHOD_2 (57)
L. 17:  84     expr ::= call (57)
L. 17:  84     return_expr ::= expr (57)
L. 17:  84-110 expr_stmt ::= expr POP_TOP (58)
L. 17:  84     stmt ::= expr_stmt (58)
L. 17:  84     stmts ::= stmt (58)
L. 17:  84     sstmt ::= stmt (58)
L. 17:  84     c_stmt ::= stmt (58)
L. 17:  84     _stmts ::= stmts (58)
L. 17:  84     stmts_opt ::= stmts (58)
L. 17:  84     _stmts ::= stmts (58)
L. 17:  84     stmts ::= sstmt (58)
L. 17:  84     c_stmts ::= c_stmt (58)
L. 17:  84     c_stmts ::= _stmts (58)
L. 17:  84     c_stmts ::= _stmts (58)
L. 16:  76-110 iflaststmtc ::= testexprc c_stmts (58)
Reduce iflaststmtc invalid by check
L. 17:  84     c_stmts_opt ::= c_stmts (58)
L. 17:  84     ifstmts_jumpc ::= c_stmts (58)
L. 16:  76-110 ifstmtc ::= testexprc ifstmts_jumpc \e__come_froms (58)
L. 16:  76-110 if_not_stmtc ::= testexprc ifstmts_jumpc \e__come_froms (58)
Reduce if_not_stmtc invalid by check
L. 16:  76     c_stmt ::= ifstmtc (58)
L. 16:  76     c_stmts ::= c_stmt (58)
L. 14:  48-110 c_stmts ::= c_stmts c_stmt (58)
L. 16:  76     else_suitec ::= c_stmts (58)
L. 14:  48     for_block ::= c_stmts (58)
L. 14:  48     c_stmts_opt ::= c_stmts (58)
L. 13:  36-110 forelselaststmt38 ::= expr get_for_iter store for_block else_suitec \e__come_froms (58)
Reduce forelselaststmt38 invalid by check
L. 13:  36-110 forelselaststmtc38 ::= expr get_for_iter store for_block else_suitec \e__come_froms (58)
Reduce forelselaststmtc38 invalid by check
L. 13:  36-110 for38 ::= expr get_for_iter store for_block \e__come_froms (58)
L. 13:  36     stmt ::= for38 (58)
               stmts ::= stmts stmt (58)
L. 13:  36     stmts ::= stmt (58)
L. 13:  36     sstmt ::= stmt (58)
L. 13:  36     c_stmt ::= stmt (58)
L. 12:  20-110 stmts ::= stmts stmt (58)
               START ::= |- stmts (58)
               _stmts ::= stmts (58)
L. 13:  36     _stmts ::= stmts (58)
               stmts ::= stmts sstmt (58)
L. 13:  36     stmts ::= sstmt (58)
L. 12:  20-110 stmts ::= stmts sstmt (58)
L. 13:  36     c_stmts ::= c_stmt (58)
L. 12:  20-110 c_stmts ::= c_stmts c_stmt (58)
               c_stmts ::= c_stmts c_stmt (58)
L. 12:  20     _stmts ::= stmts (58)
               c_stmts ::= _stmts (58)
L. 13:  36     c_stmts ::= _stmts (58)
L. 12:  20     c_stmts ::= _stmts (58)
       112-112 whileTruestmt38 ::= \e__come_froms \e_pass JUMP_LOOP (59)
Reduce whileTruestmt38 invalid by check
L. 16:  76-112 iflaststmtc ::= testexprc c_stmts JUMP_LOOP \e_opt_pop_block (59)
Reduce iflaststmtc invalid by check
L. 17:  84-112 ifstmts_jumpc ::= c_stmts JUMP_LOOP (59)
L. 17:  84-112 whileTruestmt38 ::= \e__come_froms c_stmts JUMP_LOOP \e__come_froms (59)
Reduce whileTruestmt38 invalid by check
L. 17:  84-112 whileTruestmt38 ::= \e__come_froms c_stmts JUMP_LOOP \e__come_froms (59)
Reduce whileTruestmt38 invalid by check
L. 16:  76-112 whileTruestmt38 ::= \e__come_froms c_stmts JUMP_LOOP \e__come_froms (59)
Reduce whileTruestmt38 invalid by check
L. 14:  48-112 for_block ::= c_stmts JUMP_LOOP (59)
L. 14:  48-112 whileTruestmt38 ::= \e__come_froms c_stmts JUMP_LOOP \e__come_froms (59)
Reduce whileTruestmt38 invalid by check
L. 13:  36-112 for38 ::= expr get_for_iter store for_block JUMP_LOOP \e__come_froms (59)
L. 14:  48-112 for_block ::= c_stmts_opt \e__come_froms JUMP_LOOP (59)
L. 14:  48-112 for_block ::= c_stmts_opt \e_come_from_loops JUMP_LOOP (59)
L. 14:  48-112 for_block ::= \e__come_froms c_stmts_opt \e_come_from_loops JUMP_LOOP (59)
L. 13:  36-112 whileTruestmt38 ::= \e__come_froms c_stmts JUMP_LOOP \e__come_froms (59)
Reduce whileTruestmt38 invalid by check
L. 12:  20-112 whileTruestmt38 ::= \e__come_froms c_stmts JUMP_LOOP \e__come_froms (59)
Reduce whileTruestmt38 invalid by check
               whileTruestmt38 ::= \e__come_froms c_stmts JUMP_LOOP \e__come_froms (59)
Reduce whileTruestmt38 invalid by check
L. 16:  76-112 ifstmtc ::= testexprc ifstmts_jumpc \e__come_froms (59)
L. 16:  76-112 if_not_stmtc ::= testexprc ifstmts_jumpc \e__come_froms (59)
Reduce if_not_stmtc invalid by check
L. 13:  36-112 for38 ::= expr get_for_iter store for_block \e__come_froms (59)
L. 13:  36     stmt ::= for38 (59)
L. 16:  76     c_stmt ::= ifstmtc (59)
               stmts ::= stmts stmt (59)
L. 13:  36     stmts ::= stmt (59)
L. 13:  36     sstmt ::= stmt (59)
L. 13:  36     c_stmt ::= stmt (59)
L. 12:  20-112 stmts ::= stmts stmt (59)
L. 16:  76     c_stmts ::= c_stmt (59)
L. 14:  48-112 c_stmts ::= c_stmts c_stmt (59)
               START ::= |- stmts (59)
               _stmts ::= stmts (59)
L. 13:  36     _stmts ::= stmts (59)
               stmts ::= stmts sstmt (59)
L. 13:  36     stmts ::= sstmt (59)
L. 12:  20-112 stmts ::= stmts sstmt (59)
L. 13:  36     c_stmts ::= c_stmt (59)
L. 12:  20-112 c_stmts ::= c_stmts c_stmt (59)
               c_stmts ::= c_stmts c_stmt (59)
L. 12:  20     _stmts ::= stmts (59)
L. 16:  76     else_suitec ::= c_stmts (59)
L. 14:  48     for_block ::= c_stmts (59)
L. 14:  48     c_stmts_opt ::= c_stmts (59)
               c_stmts ::= _stmts (59)
L. 13:  36     c_stmts ::= _stmts (59)
L. 12:  20     c_stmts ::= _stmts (59)
L. 13:  36-112 forelselaststmt38 ::= expr get_for_iter store for_block else_suitec \e__come_froms (59)
Reduce forelselaststmt38 invalid by check
L. 13:  36-112 forelselaststmtc38 ::= expr get_for_iter store for_block else_suitec \e__come_froms (59)
Reduce forelselaststmtc38 invalid by check
               _come_froms ::= \e__come_froms COME_FROM (60)
               whileTruestmt38 ::= \e__come_froms c_stmts JUMP_LOOP _come_froms (60)
Reduce whileTruestmt38 invalid by check
L. 16:  76-114 whileTruestmt38 ::= \e__come_froms c_stmts JUMP_LOOP _come_froms (60)
Reduce whileTruestmt38 invalid by check
L. 14:  48-114 whileTruestmt38 ::= \e__come_froms c_stmts JUMP_LOOP _come_froms (60)
Reduce whileTruestmt38 invalid by check
L. 13:  36-114 for38 ::= expr get_for_iter store for_block JUMP_LOOP _come_froms (60)
L. 13:  36-114 whileTruestmt38 ::= \e__come_froms c_stmts JUMP_LOOP _come_froms (60)
Reduce whileTruestmt38 invalid by check
L. 12:  20-114 whileTruestmt38 ::= \e__come_froms c_stmts JUMP_LOOP _come_froms (60)
Reduce whileTruestmt38 invalid by check
               whileTruestmt38 ::= \e__come_froms c_stmts JUMP_LOOP _come_froms (60)
Reduce whileTruestmt38 invalid by check
L. 16:  76-114 ifstmtc ::= testexprc ifstmts_jumpc _come_froms (60)
L. 16:  76-114 if_not_stmtc ::= testexprc ifstmts_jumpc _come_froms (60)
Reduce if_not_stmtc invalid by check
L. 13:  36-114 for38 ::= expr get_for_iter store for_block _come_froms (60)
L. 13:  36-114 forelselaststmt38 ::= expr get_for_iter store for_block else_suitec _come_froms (60)
Reduce forelselaststmt38 invalid by check
L. 13:  36-114 forelselaststmtc38 ::= expr get_for_iter store for_block else_suitec _come_froms (60)
Reduce forelselaststmtc38 invalid by check
L. 13:  36     stmt ::= for38 (60)
L. 16:  76     c_stmt ::= ifstmtc (60)
               stmts ::= stmts stmt (60)
L. 13:  36     stmts ::= stmt (60)
L. 13:  36     sstmt ::= stmt (60)
L. 13:  36     c_stmt ::= stmt (60)
L. 12:  20-114 stmts ::= stmts stmt (60)
L. 16:  76     c_stmts ::= c_stmt (60)
L. 14:  48-114 c_stmts ::= c_stmts c_stmt (60)
               START ::= |- stmts (60)
               _stmts ::= stmts (60)
L. 13:  36     _stmts ::= stmts (60)
               stmts ::= stmts sstmt (60)
L. 13:  36     stmts ::= sstmt (60)
L. 12:  20-114 stmts ::= stmts sstmt (60)
L. 13:  36     c_stmts ::= c_stmt (60)
L. 12:  20-114 c_stmts ::= c_stmts c_stmt (60)
               c_stmts ::= c_stmts c_stmt (60)
L. 12:  20     _stmts ::= stmts (60)
L. 16:  76     else_suitec ::= c_stmts (60)
L. 14:  48     for_block ::= c_stmts (60)
L. 14:  48     c_stmts_opt ::= c_stmts (60)
               c_stmts ::= _stmts (60)
L. 13:  36     c_stmts ::= _stmts (60)
L. 12:  20     c_stmts ::= _stmts (60)
L. 13:  36-114 forelselaststmt38 ::= expr get_for_iter store for_block else_suitec \e__come_froms (60)
Reduce forelselaststmt38 invalid by check
L. 13:  36-114 forelselaststmtc38 ::= expr get_for_iter store for_block else_suitec \e__come_froms (60)
Reduce forelselaststmtc38 invalid by check
L. 13:  36-114 for38 ::= expr get_for_iter store for_block \e__come_froms (60)
               expr ::= LOAD_FAST (1)
               return_expr ::= expr (1)
               attribute ::= expr LOAD_ATTR (2)
               expr ::= attribute (2)
               return_expr ::= expr (2)
               attribute37 ::= expr LOAD_METHOD (3)
               expr ::= attribute37 (3)
               return_expr ::= expr (3)
         6     expr ::= LOAD_FAST (4)
         8     expr ::= LOAD_FAST (5)
         6-10  list ::= expr expr BUILD_LIST_2 (6)
         6     expr ::= list (6)
               call ::= expr expr CALL_METHOD_1 (7)
               expr ::= call (7)
               return_expr ::= expr (7)
               expr_stmt ::= expr POP_TOP (8)
               stmt ::= expr_stmt (8)
               stmts ::= stmt (8)
               sstmt ::= stmt (8)
               c_stmt ::= stmt (8)
               START ::= |- stmts (8)
               _stmts ::= stmts (8)
               stmts ::= sstmt (8)
               c_stmts ::= c_stmt (8)
               c_stmts ::= _stmts (8)
               expr ::= LOAD_GLOBAL (1)
               return_expr ::= expr (1)
         2     expr ::= LOAD_FAST (2)
               call ::= expr expr CALL_FUNCTION_1 (3)
               expr ::= call (3)
               return_expr ::= expr (3)
               return ::= return_expr RETURN_VALUE (4)
               stmt ::= return (4)
               returns ::= return (4)
               stmts ::= stmt (4)
               sstmt ::= stmt (4)
               c_stmt ::= stmt (4)
               c_returns ::= returns (4)
               START ::= |- stmts (4)
               _stmts ::= stmts (4)
               stmts ::= sstmt (4)
               c_stmts ::= c_stmt (4)
               c_stmts ::= c_returns (4)
               c_stmts ::= _stmts (4)
               sstmt ::= return RETURN_LAST (5)
               sstmt ::= sstmt RETURN_LAST (5)
               stmts ::= sstmt (5)
               START ::= |- stmts (5)
               _stmts ::= stmts (5)
               c_stmts ::= _stmts (5)
from . import bus

class ad5206:

    def __init__(self, config):
        self.spi = bus.MCU_SPI_from_config(config,
          0, pin_option="enable_pin", default_speed=25000000)
        scale = config.getfloat("scale", 1.0, above=0.0)
        for i in range(6):
            val = config.getfloat(("channel_%d" % (i + 1,)), None, minval=0.0,
              maxval=scale)
            if val is not None:
                self.set_register(i, int(val * 256.0 / scale + 0.5))

    def set_register(self, reg, value):
        self.spi.spi_send([reg, value])


def load_config_prefix(config):
    return ad5206(config)

