# decompyle3 version 3.9.3
# Python bytecode version base 3.8.0 (3413)
# Decompiled from: Python 3.14.4 | packaged by Anaconda, Inc. | (main, Apr 14 2026, 17:00:17) [MSC v.1942 64 bit (AMD64)]
# Embedded file name: /var/jenkins_home/workspace/IngenicX2600-CFS-C-Master-Security-Build/integrated_platform/buildtools/../creality/output/build/klipper-creality/klippy/extras/box.py
# Compiled at: 2025-10-29 02:45:24
# Size of source mod 2**32: 226 bytes
               expr ::= LOAD_CONST (1)
               return_expr ::= expr (1)
         2     expr ::= LOAD_CONST (2)
         8     store ::= STORE_NAME (5)
         6-8   alias ::= IMPORT_FROM store (5)
         6     importlist ::= alias (5)
               import_from ::= LOAD_CONST LOAD_CONST IMPORT_NAME importlist POP_TOP (6)
               stmt ::= import_from (6)
               stmts ::= stmt (6)
               sstmt ::= stmt (6)
               c_stmt ::= stmt (6)
               START ::= |- stmts (6)
               _stmts ::= stmts (6)
               stmts ::= sstmt (6)
               c_stmts ::= c_stmt (6)
               c_stmts ::= _stmts (6)
L.  5:  12     expr ::= LOAD_CODE (7)
L.  5:  12     expr ::= LOAD_CODE (7)
L.  5:  12     return_expr ::= expr (7)
L.  5:  12     return_expr ::= expr (7)
        14     expr ::= LOAD_STR (8)
L.  5:  12-16  mkfunc ::= LOAD_CODE LOAD_STR MAKE_FUNCTION_0 (9)
               store ::= STORE_NAME (10)
               function_def ::= mkfunc store (10)
               stmt ::= function_def (10)
               stmts ::= stmts stmt (10)
               stmts ::= stmt (10)
               sstmt ::= stmt (10)
               c_stmt ::= stmt (10)
               START ::= |- stmts (10)
               _stmts ::= stmts (10)
               _stmts ::= stmts (10)
               stmts ::= stmts sstmt (10)
               stmts ::= sstmt (10)
               c_stmts ::= c_stmt (10)
               c_stmts ::= c_stmts c_stmt (10)
               c_stmts ::= _stmts (10)
               c_stmts ::= _stmts (10)
               expr ::= LOAD_GLOBAL (1)
               return_expr ::= expr (1)
         2     expr ::= LOAD_FAST (2)
               call ::= expr expr CALL_FUNCTION_1 (3)
               expr ::= call (3)
               return_expr ::= expr (3)
               return ::= return_expr RETURN_VALUE (4)
               stmt ::= return (4)
               returns ::= return (4)
               stmts ::= stmt (4)
               sstmt ::= stmt (4)
               c_stmt ::= stmt (4)
               c_returns ::= returns (4)
               START ::= |- stmts (4)
               _stmts ::= stmts (4)
               stmts ::= sstmt (4)
               c_stmts ::= c_stmt (4)
               c_stmts ::= c_returns (4)
               c_stmts ::= _stmts (4)
               sstmt ::= return RETURN_LAST (5)
               sstmt ::= sstmt RETURN_LAST (5)
               stmts ::= sstmt (5)
               START ::= |- stmts (5)
               _stmts ::= stmts (5)
               c_stmts ::= _stmts (5)
from .box_control import MulticolorBoxController

def load_config(config):
    return MulticolorBoxController(config)

