# decompyle3 version 3.9.3
# Python bytecode version base 3.8.0 (3413)
# Decompiled from: Python 3.14.4 | packaged by Anaconda, Inc. | (main, Apr 14 2026, 17:00:17) [MSC v.1942 64 bit (AMD64)]
# Embedded file name: /var/jenkins_home/workspace/IngenicX2600-CFS-C-Master-Security-Build/integrated_platform/buildtools/../creality/output/build/klipper-creality/klippy/extras/heater_generic.py
# Compiled at: 2025-10-29 02:45:24
# Size of source mod 2**32: 302 bytes
               expr ::= LOAD_CODE (1)
               return_expr ::= expr (1)
         2     expr ::= LOAD_STR (2)
               mkfunc ::= LOAD_CODE LOAD_STR MAKE_FUNCTION_0 (3)
               store ::= STORE_NAME (4)
               function_def ::= mkfunc store (4)
               stmt ::= function_def (4)
               stmts ::= stmt (4)
               sstmt ::= stmt (4)
               c_stmt ::= stmt (4)
               START ::= |- stmts (4)
               _stmts ::= stmts (4)
               stmts ::= sstmt (4)
               c_stmts ::= c_stmt (4)
               c_stmts ::= _stmts (4)
               expr ::= LOAD_FAST (1)
               return_expr ::= expr (1)
               attribute37 ::= expr LOAD_METHOD (2)
               expr ::= attribute37 (2)
               return_expr ::= expr (2)
               call ::= expr CALL_METHOD_0 (3)
               expr ::= call (3)
               return_expr ::= expr (3)
               attribute37 ::= expr LOAD_METHOD (4)
               expr ::= attribute37 (4)
               return_expr ::= expr (4)
         8     expr ::= LOAD_FAST (5)
        10     expr ::= LOAD_STR (6)
               call ::= expr expr expr CALL_METHOD_2 (7)
               expr ::= call (7)
               return_expr ::= expr (7)
        14     store ::= STORE_FAST (8)
               assign ::= expr store (8)
               stmt ::= assign (8)
               stmts ::= stmt (8)
               sstmt ::= stmt (8)
               c_stmt ::= stmt (8)
               START ::= |- stmts (8)
               _stmts ::= stmts (8)
               stmts ::= sstmt (8)
               c_stmts ::= c_stmt (8)
               c_stmts ::= _stmts (8)
L.  9:  16     expr ::= LOAD_FAST (9)
L.  9:  16     return_expr ::= expr (9)
L.  9:  16     return_expr ::= expr (9)
L.  9:  16-18  attribute37 ::= expr LOAD_METHOD (10)
L.  9:  16     expr ::= attribute37 (10)
L.  9:  16     return_expr ::= expr (10)
L.  9:  16     return_expr ::= expr (10)
        20     expr ::= LOAD_FAST (11)
L.  9:  16-22  call ::= expr expr CALL_METHOD_1 (12)
L.  9:  16     expr ::= call (12)
L.  9:  16     return_expr ::= expr (12)
L.  9:  16     return_expr ::= expr (12)
L.  9:  16-24  return ::= return_expr RETURN_VALUE (13)
L.  9:  16     stmt ::= return (13)
L.  9:  16     returns ::= return (13)
               returns ::= _stmts return (13)
               c_returns ::= c_stmts return (13)
               stmts ::= stmts stmt (13)
L.  9:  16     stmts ::= stmt (13)
L.  9:  16     sstmt ::= stmt (13)
L.  9:  16     c_stmt ::= stmt (13)
L.  9:  16     c_returns ::= returns (13)
               c_returns ::= returns (13)
               c_stmts ::= c_returns (13)
               START ::= |- stmts (13)
               _stmts ::= stmts (13)
L.  9:  16     _stmts ::= stmts (13)
               stmts ::= stmts sstmt (13)
L.  9:  16     stmts ::= sstmt (13)
L.  9:  16     c_stmts ::= c_stmt (13)
               c_stmts ::= c_stmts c_stmt (13)
L.  9:  16     c_stmts ::= c_returns (13)
               c_stmts ::= _stmts (13)
L.  9:  16     c_stmts ::= _stmts (13)
               sstmt ::= return RETURN_LAST (14)
               sstmt ::= sstmt RETURN_LAST (14)
               stmts ::= stmts sstmt (14)
               stmts ::= sstmt (14)
               START ::= |- stmts (14)
               _stmts ::= stmts (14)
               _stmts ::= stmts (14)
               c_stmts ::= _stmts (14)
               c_stmts ::= _stmts (14)


def load_config_prefix(config):
    pheaters = config.get_printer().load_object(config, "heaters")
    return pheaters.setup_heater(config)

